spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?characterEncoding=UTF-8&useUnicode=true&serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    username: ${REDIS_USERNAME}
    password: ${REDIS_PASSWORD}
    ssl: false
  jpa:
    open-in-view: false
jwt:
  access-token-expiration-ms: ${JWT_EXPIRATION_MS}
  secret-key: ${JWT_SECRET_KEY}
cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}