version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/deploy
    overwrite: true

permissions:
  - object: /home/ubuntu/deploy/scripts
    pattern: "**"
    mode: 755
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 60
      runas: ubuntu
  
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 120
      runas: ubuntu
  
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: ubuntu


