version: 0.0
os: linux

files:
  - source: /
    destination: /opt/backend-app
    overwrite: yes
    file_exists_behavior: OVERWRITE

permissions:
  - object: /opt/backend-app
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
  - object: /opt/backend-app
    pattern: "**/*.sh"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ubuntu

  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/manage_images.sh
      timeout: 600
      runas: ubuntu
    - location: scripts/start_application.sh
      timeout: 300
      runas: ubuntu

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: ubuntu
    - location: scripts/cleanup_s3.sh
      timeout: 300
      runas: ubuntu

