# MySQL Setting
spring:
  datasource:
    url: jdbc:mysql://localhost:3306?characterEncoding=UTF-8&useUnicode=true&serverTimezone=Asia/Seoul
    username: @YOUR_USERNAME@
    password: @YOUR_PASSWORD@
    driver-class-name: com.mysql.cj.jdbc.Driver