# 파일 이름: docker-compose.yml
services:
  api-server:
    image: api-server:${IMAGE_TAG:-latest}
    container_name: api-server
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-3306}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - backend-network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  batch-server:
    image: batch-server:${IMAGE_TAG:-latest}
    container_name: batch-server
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-3306}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - BATCH_JOB_ENABLED=true
    networks:
      - backend-network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

networks:
  backend-network:
    driver: bridge