# scripts/deploy/docker-compose.prod.yml

services:
  api-server:
    image: api-server:${IMAGE_TAG:-latest}
    container_name: api-server
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=backend_db
      - DB_USER=backend_user
      - DB_PASSWORD=backend_pass
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - backend-network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  batch-server:
    image: batch-server:${IMAGE_TAG:-latest}
    container_name: batch-server
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=backend_db
      - DB_USER=backend_user
      - DB_PASSWORD=backend_pass
      - BATCH_JOB_ENABLED=true
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - backend-network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  test-server:
    image: test-server:${IMAGE_TAG:-latest}
    container_name: test-server
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=backend_db
      - DB_USER=backend_user
      - DB_PASSWORD=backend_pass
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - backend-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_pass}
      MYSQL_DATABASE: backend_db
      MYSQL_USER: backend_user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-backend_pass}
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - backend-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

networks:
  backend-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
