spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?characterEncoding=UTF-8&useUnicode=true&serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    username: ${REDIS_USERNAME}
    password: ${REDIS_PASSWORD}
  batch:
    job:
      enabled: false

kma:
  api:
    key:
      mountain: ${secrets.KMA_API_KEY_MOUNTAIN}
      short: ${secrets.KMA_API_KEY_SHORT}
      ultra: ${secrets.KMA_API_KEY_ULTRA}

forecast:
  mapping:
    sky:
      "1.0": "SUNNY"
      "1": "SUNNY"
      "3.0": "CLOUDY"
      "3": "CLOUDY"
      "4.0": "OVERCAST"
      "4": "OVERCAST"
    precipitation-type:
      "0": "NONE"
      "1": "RAIN"
      "2": "RAIN_SNOW"
      "3": "SNOW"
      "4": "SHOWER"
      "5": "DRIZZLE"
      "6": "DRIZZLE_SNOW"
      "7": "SNOW_FLURRY"